INSERT INTO `producto` VALUES (150,'N/A','La dorada (Esparus Aurata), muy consumida y valorada dentro de la gastronomía española.',400,'El pescado fresco siempre ha de mantenerse a una temperatura de entre 0 y 4º C','Ha pasado los controles determinados por la CE','La dorada, de la familia de los espáridos, es un pez que se caracteriza por tener un cuerpo alto, ovalado y comprimido, con una larga aleta dorsal. Cabeza alta, compacta y con frente muy arqueada o convexa. Ojo pequeño y mejillas con escamas, que llegan hasta debajo del ojo y hasta la parte posterior de la nuca por encima de la cabeza. Labios gruesos, boca baja con una dentadura poderosa preparada para triturar moluscos.',1,'Dorada','dorada.jpg',3.96,20,21,'Kilo','gramos',8);

INSERT INTO `producto` VALUES (151,'N/A','La trucha (Oncorhynchus Mykiss) es un pescado semigraso de carne muy sabrosa',300,'El pescado fresco siempre ha de mantenerse a una temperatura de entre 0 y 4º C','Ha pasado los controles determinados por la CE','La trucha, Oncorhynchus mykiss, de la familia de los salmónidos, tiene su origen —a nivel comercial— en la acuicultura. Este pescado es de forma fusiforme, cuerpo alargado comprimido, con tronco caudal alto. Lo más característico y diferencial respecto a otros afines es una banda de colores irisados en verde, rojo y azul, «arco iris», situada a lo largo de cada lado del cuerpo, que es la que le confiere su nombre, más perceptible con el efecto del agua y el sol.',1,'Trucha','trucha.jpg',3.16,20,21,'Kilo','gramos',8);

INSERT INTO `producto` VALUES (152,'N/A','El salmón (Salmo Salar) es un pescado azul muy demandado',7,'El pescado fresco siempre ha de mantenerse a una temperatura de entre 0 y 4º C','Ha pasado los controles determinados por la CE','El salmón de la familia de los salmónidos, es un habitante de aguas frías, dulces y saladas, buen nadador, de cuerpo cubierto por escamas, poderosa musculatura y voraz, que se alimenta de crustáceos y otros peces. Dispone de una gran boca, aunque no llega a alcanzar la vertical del centro del ojo, con fuertes dientes.',1,'Salmón','salmon.jpg',76.30,20,21,'Kilo','kilo',8);

INSERT INTO `producto` VALUES (153,'N/A','El calamar (Loligo Reynaud) es un producto que está presente en la cultura gastronómica de España',500,'Mantener a una temperatura entre 0° y 4°.  Producto descongelado, no volver a congelar.','Ha pasado los controles determinados por la CE','El calamar se caracteriza por su cuerpo musculoso, alargado con forma de cilindro comprimido y afilado, terminado con dos aletas triangulares negras, a modo de torpedo. Formado por dos regiones: la cabeza, cercana a los brazos, donde se hallan los ojos con párpados transparentes y la boca; y el manto, donde se aloja la «pluma» o esqueleto de naturaleza córnea, indicio de la concha de otros cefalópodos, que fortalece al animal y participa en su movimiento.',1,'Calamar','calamar.jpg',7.30,20,21,'Kilo','gramos',8);

INSERT INTO `producto` VALUES (154,'N/A','La palometa, también conocida como japuta, es uno de los pescados mas abundantes y consumidos',900,'El pescado fresco siempre ha de mantenerse a una temperatura de entre 0 y 4º C.','Ha pasado los controles determinados por la CE','La japuta o palometa negra, con nombre científico Brama brama, es un pez que pertenece a la familia de los brámidos, dentro del orden de los Perciformes. Con cuerpo de altura moderada y comprimido lateralmente. Su boca es grande y oblicua. Sus ojos, saltones. De color gris plomizo, casi negro.',1,'Palometa','palometa.jpg',11.88,20,21,'Kilo','gramos',8);

INSERT INTO `producto` VALUES (155,'N/A','Al rodaballo se le considera como uno de los mejores y más sobrosos pescados.',1200,'El pescado fresco siempre ha de mantenerse a una temperatura de entre 0 y 4º C.','Ha pasado los controles determinados por la CE','El rodaballo, Scophtalmus maximus, de la familia de los escoftálmidos, es un pez plano, pero más grueso que los lenguados. Forma casi circular. Cabeza relativamente grande. Ojos sobre el lado izquierdo, mira a la izquierda, relativamente alejados al aparecer una cresta ósea entre ambos. Boca grande y mandíbula inferior prominente con dientes pequeños y puntiagudos.',1,'Rodaballo','rodaballo.jpg',23.66,20,21,'Kilo','gramos',8);

INSERT INTO `producto` VALUES (156,'N/A','El rape es un pescado blanco que destaca por su gran cantidad de proteínas y pocas grasas.',1300,'El pescado fresco siempre ha de mantenerse a una temperatura de entre 0 y 4º C.','Ha pasado los controles determinados por la CE','El rape común o rape blanco es un pez sin espinas  y de color pardo jaspeado en tonos violáceos o rojizos, según la especie. La forma irregular de su cuerpo, junto con el color de su piel, le permiten mimetizarse en su medio.',1,'Rape Negro','rapeNegro.jpg',18.06,20,21,'Kilo','gramos',8);

INSERT INTO `producto` VALUES (157,'N/A','Es muy valorado en la gastronomía por su carne blanca, compacta y de sabor extraordinario.',700,'El pescado fresco siempre ha de mantenerse a una temperatura de entre 0 y 4º C.','Ha pasado los controles determinados por la CE','El cuerpo es de color rosa intenso en el dorso, y va palideciendo hacia la parte ventral. Los flancos presentan 5 o 6 anchas bandas transversales más oscuras y de contorno irregular. La aleta dorsal presenta una mancha oscura, que no siempre es conspicua, situada sobre los últimos radios.',1,'Cabra','cabra.jpg',8.07,20,21,'Kilo','gramos',8);

INSERT INTO `producto` VALUES (160,'N/A','La dorada (Esparus Aurata), muy consumida y valorada dentro de la gastronomía española.',400,'El pescado fresco siempre ha de mantenerse a una temperatura de entre 0 y 4º C','Ha pasado los controles determinados por la CE','La dorada, de la familia de los espáridos, es un pez que se caracteriza por tener un cuerpo alto, ovalado y comprimido, con una larga aleta dorsal. Cabeza alta, compacta y con frente muy arqueada o convexa. Ojo pequeño y mejillas con escamas, que llegan hasta debajo del ojo y hasta la parte posterior de la nuca por encima de la cabeza. Labios gruesos, boca baja con una dentadura poderosa preparada para triturar moluscos.',1,'Dorada','dorada.jpg',3.96,20,21,'Kilo','gramos',10);

INSERT INTO `producto` VALUES (161,'N/A','La trucha (Oncorhynchus Mykiss) es un pescado semigraso de carne muy sabrosa',300,'El pescado fresco siempre ha de mantenerse a una temperatura de entre 0 y 4º C','Ha pasado los controles determinados por la CE','La trucha, Oncorhynchus mykiss, de la familia de los salmónidos, tiene su origen —a nivel comercial— en la acuicultura. Este pescado es de forma fusiforme, cuerpo alargado comprimido, con tronco caudal alto. Lo más característico y diferencial respecto a otros afines es una banda de colores irisados en verde, rojo y azul, «arco iris», situada a lo largo de cada lado del cuerpo, que es la que le confiere su nombre, más perceptible con el efecto del agua y el sol.',1,'Trucha','trucha.jpg',3.16,20,21,'Kilo','gramos',10);

INSERT INTO `producto` VALUES (162,'N/A','El salmón (Salmo Salar) es un pescado azul muy demandado',7,'El pescado fresco siempre ha de mantenerse a una temperatura de entre 0 y 4º C','Ha pasado los controles determinados por la CE','El salmón de la familia de los salmónidos, es un habitante de aguas frías, dulces y saladas, buen nadador, de cuerpo cubierto por escamas, poderosa musculatura y voraz, que se alimenta de crustáceos y otros peces. Dispone de una gran boca, aunque no llega a alcanzar la vertical del centro del ojo, con fuertes dientes.',1,'Salmón','salmon.jpg',76.30,20,21,'Kilo','kilo',10);

INSERT INTO `producto` VALUES (163,'N/A','El calamar (Loligo Reynaud) es un producto que está presente en la cultura gastronómica de España',500,'Mantener a una temperatura entre 0° y 4°.  Producto descongelado, no volver a congelar.','Ha pasado los controles determinados por la CE','El calamar se caracteriza por su cuerpo musculoso, alargado con forma de cilindro comprimido y afilado, terminado con dos aletas triangulares negras, a modo de torpedo. Formado por dos regiones: la cabeza, cercana a los brazos, donde se hallan los ojos con párpados transparentes y la boca; y el manto, donde se aloja la «pluma» o esqueleto de naturaleza córnea, indicio de la concha de otros cefalópodos, que fortalece al animal y participa en su movimiento.',1,'Calamar','calamar.jpg',7.30,20,21,'Kilo','gramos',10);

INSERT INTO `producto` VALUES (164,'N/A','La palometa, también conocida como japuta, es uno de los pescados mas abundantes y consumidos',900,'El pescado fresco siempre ha de mantenerse a una temperatura de entre 0 y 4º C.','Ha pasado los controles determinados por la CE','La japuta o palometa negra, con nombre científico Brama brama, es un pez que pertenece a la familia de los brámidos, dentro del orden de los Perciformes. Con cuerpo de altura moderada y comprimido lateralmente. Su boca es grande y oblicua. Sus ojos, saltones. De color gris plomizo, casi negro.',1,'Palometa','palometa.jpg',11.88,20,21,'Kilo','gramos',10);

INSERT INTO `producto` VALUES (165,'N/A','Al rodaballo se le considera como uno de los mejores y más sobrosos pescados.',1200,'El pescado fresco siempre ha de mantenerse a una temperatura de entre 0 y 4º C.','Ha pasado los controles determinados por la CE','El rodaballo, Scophtalmus maximus, de la familia de los escoftálmidos, es un pez plano, pero más grueso que los lenguados. Forma casi circular. Cabeza relativamente grande. Ojos sobre el lado izquierdo, mira a la izquierda, relativamente alejados al aparecer una cresta ósea entre ambos. Boca grande y mandíbula inferior prominente con dientes pequeños y puntiagudos.',1,'Rodaballo','rodaballo.jpg',23.66,20,21,'Kilo','gramos',10);

INSERT INTO `producto` VALUES (172,'N/A','El salmón (Salmo Salar) es un pescado azul muy demandado',7,'El pescado fresco siempre ha de mantenerse a una temperatura de entre 0 y 4º C','Ha pasado los controles determinados por la CE','El salmón de la familia de los salmónidos, es un habitante de aguas frías, dulces y saladas, buen nadador, de cuerpo cubierto por escamas, poderosa musculatura y voraz, que se alimenta de crustáceos y otros peces. Dispone de una gran boca, aunque no llega a alcanzar la vertical del centro del ojo, con fuertes dientes.',1,'Salmón','salmon.jpg',76.30,20,21,'Kilo','kilo',15);

INSERT INTO `producto` VALUES (173,'N/A','El calamar (Loligo Reynaud) es un producto que está presente en la cultura gastronómica de España',500,'Mantener a una temperatura entre 0° y 4°.  Producto descongelado, no volver a congelar.','Ha pasado los controles determinados por la CE','El calamar se caracteriza por su cuerpo musculoso, alargado con forma de cilindro comprimido y afilado, terminado con dos aletas triangulares negras, a modo de torpedo. Formado por dos regiones: la cabeza, cercana a los brazos, donde se hallan los ojos con párpados transparentes y la boca; y el manto, donde se aloja la «pluma» o esqueleto de naturaleza córnea, indicio de la concha de otros cefalópodos, que fortalece al animal y participa en su movimiento.',1,'Calamar','calamar.jpg',7.30,20,21,'Kilo','gramos',15);

INSERT INTO `producto` VALUES (174,'N/A','La palometa, también conocida como japuta, es uno de los pescados mas abundantes y consumidos',900,'El pescado fresco siempre ha de mantenerse a una temperatura de entre 0 y 4º C.','Ha pasado los controles determinados por la CE','La japuta o palometa negra, con nombre científico Brama brama, es un pez que pertenece a la familia de los brámidos, dentro del orden de los Perciformes. Con cuerpo de altura moderada y comprimido lateralmente. Su boca es grande y oblicua. Sus ojos, saltones. De color gris plomizo, casi negro.',1,'Palometa','palometa.jpg',11.88,20,21,'Kilo','gramos',15);

INSERT INTO `producto` VALUES (175,'N/A','Al rodaballo se le considera como uno de los mejores y más sobrosos pescados.',1200,'El pescado fresco siempre ha de mantenerse a una temperatura de entre 0 y 4º C.','Ha pasado los controles determinados por la CE','El rodaballo, Scophtalmus maximus, de la familia de los escoftálmidos, es un pez plano, pero más grueso que los lenguados. Forma casi circular. Cabeza relativamente grande. Ojos sobre el lado izquierdo, mira a la izquierda, relativamente alejados al aparecer una cresta ósea entre ambos. Boca grande y mandíbula inferior prominente con dientes pequeños y puntiagudos.',1,'Rodaballo','rodaballo.jpg',23.66,20,21,'Kilo','gramos',15);

INSERT INTO `producto` VALUES (176,'N/A','El rape es un pescado blanco que destaca por su gran cantidad de proteínas y pocas grasas.',1300,'El pescado fresco siempre ha de mantenerse a una temperatura de entre 0 y 4º C.','Ha pasado los controles determinados por la CE','El rape común o rape blanco es un pez sin espinas  y de color pardo jaspeado en tonos violáceos o rojizos, según la especie. La forma irregular de su cuerpo, junto con el color de su piel, le permiten mimetizarse en su medio.',1,'Rape Negro','rapeNegro.jpg',18.06,20,21,'Kilo','gramos',15);

INSERT INTO `producto` VALUES (177,'N/A','Es muy valorado en la gastronomía por su carne blanca, compacta y de sabor extraordinario.',700,'El pescado fresco siempre ha de mantenerse a una temperatura de entre 0 y 4º C.','Ha pasado los controles determinados por la CE','El cuerpo es de color rosa intenso en el dorso, y va palideciendo hacia la parte ventral. Los flancos presentan 5 o 6 anchas bandas transversales más oscuras y de contorno irregular. La aleta dorsal presenta una mancha oscura, que no siempre es conspicua, situada sobre los últimos radios.',1,'Cabra','cabra.jpg',8.07,20,21,'Kilo','gramos',15);

INSERT INTO `producto` VALUES (181,'N/A','La chuleta es uno de los cortes más apreciados del cerdo',500,'La carne siempre ha de mantenerse a una temperatura de entre -1 y 2º C.','Ha pasado los controles determinados por la CE','Con un precio asequible, sabrosa y tierna, permite preparar platos consistentes y muy fáciles de cocinar.',1,'Chuletas de cerdo blanco','chuletaCerdoBlanco.jpg',3.25,20,21,'Kilo','gramos',9);

INSERT INTO `producto` VALUES (182,'N/A','El solomillo es una pieza de carne procedente de la parte lumbar.',400,'La carne siempre ha de mantenerse a una temperatura de entre -1 y 2º C.','Ha pasado los controles determinados por la CE','Consta de varias partes: la cabeza, el rosario, el centro y la punta.',1,'Solomillo de cerdo blanco','solomilloCerdo.jpg',3.71,20,21,'Kilo','gramos',9);

INSERT INTO `producto` VALUES (183,'N/A','También se suele llamar presa a la bola ibérica, la parte más tierna de la aguja.',600,'La carne siempre ha de mantenerse a una temperatura de entre -1 y 2º C.','Ha pasado los controles determinados por la CE','Es una de las piezas más apreciadas del cerdo ibérico por su jugosidad e infiltración de grasa.',1,'Presa iberica','presaIberica.jpg',10.29,20,21,'Kilo','gramos',9);

INSERT INTO `producto` VALUES (184,'N/A','El redondo de ternera es una especie de lomo, situado en la parte alta de las patas traseras.',2,'La carne siempre ha de mantenerse a una temperatura de entre -1 y 2º C.','Ha pasado los controles determinados por la CE','Carne tierna, su característica forma la define: redonda, sin nervios y con poca grasa, procedente de los cuartos traseros. Es una pieza ideal para asados, guisos, mechados',1,'Redondo de ternera','redondoDeTernera.jpg',10.54,20,21,'Kilo','kilo',9);

INSERT INTO `producto` VALUES (185,'N/A','Una de las mejores piezas de la ternera para comer a la brasa o plancha.',400,'La carne siempre ha de mantenerse a una temperatura de entre -1 y 2º C.','Ha pasado los controles determinados por la CE','Hembras de vacuno de origen español alimentadas a base de cereales un mínimo de 6 meses.',1,'Entrecot de ternera','entrecot-de-ternera.jpg',5.54,20,21,'Kilo','gramos',9);

INSERT INTO `producto` VALUES (186,'N/A','Churrasco de ternera',950,'La carne siempre ha de mantenerse a una temperatura de entre -1 y 2º C.','Ha pasado los controles determinados por la CE','Despiece que se obtiene de la falda de la ternera cortada transversalmente y no siguiendo la forma de la costilla.',1,'Churrasco de ternera','churrasco.jpg',4.90,20,21,'Kilo','gramos',9);

INSERT INTO `producto` VALUES (187,'N/A','Cuartos traseros de pollo',250,'La carne siempre ha de mantenerse a una temperatura de entre -1 y 2º C.','Ha pasado los controles determinados por la CE','N/A ',1,'Cuartos traseros de pollo','muslo-de-pollo-traseros.jpg',1.95,20,21,'Kilo','gramos',9);

INSERT INTO `producto` VALUES (188,'N/A','Pechuga de pollo entera',380,'La carne siempre ha de mantenerse a una temperatura de entre -1 y 2º C.','Ha pasado los controles determinados por la CE','N/A ',1,'Pechuga de pollo','pechuga-de-pollo-entera.jpg',2.01,20,21,'Kilo','gramos',9);

INSERT INTO `producto` VALUES (189,'N/A','Pollo entero',2,'La carne siempre ha de mantenerse a una temperatura de entre -1 y 2º C.','Ha pasado los controles determinados por la CE','N/A ',1,'Pollo entero','pollos-enteros.jpg',1.71,20,21,'Kilo','kilo',9);

INSERT INTO `producto` VALUES (192,'N/A','El solomillo es una pieza de carne procedente de la parte lumbar.',400,'La carne siempre ha de mantenerse a una temperatura de entre -1 y 2º C.','Ha pasado los controles determinados por la CE','Consta de varias partes: la cabeza, el rosario, el centro y la punta.',1,'Solomillo de cerdo blanco','solomilloCerdo.jpg',3.71,20,21,'Kilo','gramos',12);

INSERT INTO `producto` VALUES (193,'N/A','También se suele llamar presa a la bola ibérica, la parte más tierna de la aguja.',600,'La carne siempre ha de mantenerse a una temperatura de entre -1 y 2º C.','Ha pasado los controles determinados por la CE','Es una de las piezas más apreciadas del cerdo ibérico por su jugosidad e infiltración de grasa.',1,'Presa iberica','presaIberica.jpg',10.29,20,21,'Kilo','gramos',12);

INSERT INTO `producto` VALUES (194,'N/A','El redondo de ternera es una especie de lomo, situado en la parte alta de las patas traseras.',2,'La carne siempre ha de mantenerse a una temperatura de entre -1 y 2º C.','Ha pasado los controles determinados por la CE','Carne tierna, su característica forma la define: redonda, sin nervios y con poca grasa, procedente de los cuartos traseros. Es una pieza ideal para asados, guisos, mechados',1,'Redondo de ternera','redondoDeTernera.jpg',10.54,20,21,'Kilo','kilo',12);

INSERT INTO `producto` VALUES (195,'N/A','Una de las mejores piezas de la ternera para comer a la brasa o plancha.',400,'La carne siempre ha de mantenerse a una temperatura de entre -1 y 2º C.','Ha pasado los controles determinados por la CE','Hembras de vacuno de origen español alimentadas a base de cereales un mínimo de 6 meses.',1,'Entrecot de ternera','entrecot-de-ternera.jpg',5.54,20,21,'Kilo','gramos',12);

INSERT INTO `producto` VALUES (196,'N/A','Churrasco de ternera',950,'La carne siempre ha de mantenerse a una temperatura de entre -1 y 2º C.','Ha pasado los controles determinados por la CE','Despiece que se obtiene de la falda de la ternera cortada transversalmente y no siguiendo la forma de la costilla.',1,'Churrasco de ternera','churrasco.jpg',4.90,20,21,'Kilo','gramos',12);

INSERT INTO `producto` VALUES (197,'N/A','Cuartos traseros de pollo',250,'La carne siempre ha de mantenerse a una temperatura de entre -1 y 2º C.','Ha pasado los controles determinados por la CE','N/A ',1,'Cuartos traseros de pollo','muslo-de-pollo-traseros.jpg',1.95,20,21,'Kilo','gramos',12);

INSERT INTO `producto` VALUES (198,'N/A','Pechuga de pollo entera',380,'La carne siempre ha de mantenerse a una temperatura de entre -1 y 2º C.','Ha pasado los controles determinados por la CE','N/A ',1,'Pechuga de pollo','pechuga-de-pollo-entera.jpg',2.01,20,21,'Kilo','gramos',12);

INSERT INTO `producto` VALUES (199,'N/A','Pollo entero',2,'La carne siempre ha de mantenerse a una temperatura de entre -1 y 2º C.','Ha pasado los controles determinados por la CE','N/A ',1,'Pollo entero','pollos-enteros.jpg',1.71,20,21,'Kilo','kilo',12);

INSERT INTO `producto` VALUES (201,'N/A','Una de las tartas más famosas de nuestro obrador.',1,'Mantener en frio','Ha pasado los controles determinados por la CE','Delicioso pastel tierno y jugoso, que combina sabores mediterráneos como la zanahoria, la piña, las nueces y la canela y otras especias.',1,'Tarta de zanahoria','tartaZanahoria.jpeg',20,6,21,'Unidad','unidad',11);

INSERT INTO `producto` VALUES (202,'N/A','Una refrescante tarta.',1,'Mantener en frio','Ha pasado los controles determinados por la CE','Conjuga el delicioso bizcocho de limón con la confitura de mora, todo ello cubierto de frosting y finas láminas de almendras',1,'Tarta de limon y moras','tartaLimon.jpeg',20,6,21,'Unidad','unidad',11);

INSERT INTO `producto` VALUES (203,'N/A','Tarta Red Velvet.',1,'Mantener en frio','Ha pasado los controles determinados por la CE','Un poco de fantasía roja, ya que el color rojo del bizcocho es lo que caracteriza esta tarta, además de su exquisita jugosidad. Con un sabor delicado a vainilla, y cubiertos con una crema de queso blanco que intensifica su color y sabor.',1,'Tarta Red Velvet','tartaRedVelvet.jpeg',20,6,21,'Unidad','unidad',11);

INSERT INTO `producto` VALUES (204,'N/A','La delicadeza y exquisitez de esta tarta hace de ella una de las favoritas de nuestros clientes.',1,'Mantener en frio','Ha pasado los controles determinados por la CE','Es un suave bizcocho en el que la calabaza endulza y da un original sabor a esta tarta cuyas capas se rellenan con nuestro Frosting que no contiene mantequilla, es delicioso y con una textura que acompaña en perfecta armonía el bizcocho.',1,'Tarta de Calabaza','tartaCalabaza.jpeg',20,6,21,'Unidad','unidad',11);

INSERT INTO `producto` VALUES (205,'N/A','Ideal para tomar templado con un poco de frosting o helado.1kg aprox',1,'Mantener en frio','Ha pasado los controles determinados por la CE','Sin duda un dulce que crea adictos, su jugoso relleno con manzana, pera, nueces, pasas maceradas en ron y Cointreau, albaricoque y ciruelas se envuelve con una trenza de exquisito hojaldre.',1,'Strudel de Manzana y Pera','strudel.jpeg',20,6,21,'Unidad','unidad',11);

INSERT INTO `producto` VALUES (206,'N/A','Ideal para tomar en el desayuno o en la merienda',380,'Mantener en frio','Ha pasado los controles determinados por la CE','Sin duda un dulce que crea adictos.',1,'Palmera XXL de chocolate','palmeraChocolate.webp',6,8,21,'Kilo','kilo',11);

INSERT INTO `producto` VALUES (210,'N/A','Tarta Red Velvet.',1,'Mantener en frio','Ha pasado los controles determinados por la CE','Un poco de fantasía roja, ya que el color rojo del bizcocho es lo que caracteriza esta tarta, además de su exquisita jugosidad. Con un sabor delicado a vainilla, y cubiertos con una crema de queso blanco que intensifica su color y sabor.',1,'Tarta Red Velvet','tartaRedVelvet.jpeg',20,6,21,'Unidad','unidad',16);

INSERT INTO `producto` VALUES (211,'N/A','La delicadeza y exquisitez de esta tarta hace de ella una de las favoritas de nuestros clientes.',1,'Mantener en frio','Ha pasado los controles determinados por la CE','Es un suave bizcocho en el que la calabaza endulza y da un original sabor a esta tarta cuyas capas se rellenan con nuestro Frosting que no contiene mantequilla, es delicioso y con una textura que acompaña en perfecta armonía el bizcocho.',1,'Tarta de Calabaza','tartaCalabaza.jpeg',20,6,21,'Unidad','unidad',16);

INSERT INTO `producto` VALUES (212,'N/A','Ideal para tomar templado con un poco de frosting o helado.1kg aprox',1,'Mantener en frio','Ha pasado los controles determinados por la CE','Sin duda un dulce que crea adictos, su jugoso relleno con manzana, pera, nueces, pasas maceradas en ron y Cointreau, albaricoque y ciruelas se envuelve con una trenza de exquisito hojaldre.',1,'Strudel de Manzana y Pera','strudel.jpeg',20,6,21,'Unidad','unidad',16);

INSERT INTO `producto` VALUES (213,'N/A','Ideal para tomar en el desayuno o en la merienda',380,'Mantener en frio','Ha pasado los controles determinados por la CE','Sin duda un dulce que crea adictos.',1,'Palmera XXL de chocolate','palmeraChocolate.webp',6,8,21,'Kilo','kilo',16);

INSERT INTO `producto` VALUES (220,'N/A','Pieza de 600grs',1,'Mantener en frio','Ha pasado los controles determinados por la CE','Gracias a su gran riqueza en nutrientes, la espelta es un gran aliado para nuestra salud, apoyando de forma saludable sus funciones en el sistema cardiovascular.',1,'Pan Espelta','Pan-espelta-artesano.webp',4.5,10,21,'Unidad','unidad',13);

INSERT INTO `producto` VALUES (221,'N/A','Pieza de 1kg',1,'Mantener en frio','Ha pasado los controles determinados por la CE','El pan de centeno está hecho con harina de centeno y mezclado con un poco de trigo.',1,'Pan de Centeno','pan-de-centeno-puro.jpg',2.5,10,21,'Unidad','unidad',13);

INSERT INTO `producto` VALUES (223,'N/A','Pieza de 1kg',1,'Mantener en frio','Ha pasado los controles determinados por la CE','Pan tradicional de trigo con moño, elaborado con una masa de hidratación muy alta.',1,'Pan de Centeno','pan-de-trigo.jpg',2.5,10,21,'Unidad','unidad',13);

INSERT INTO `producto` VALUES (230,'N/A','Staedtler Noris 120 Lápiz de grafito',1,'N/A','Dispone de marcado CE','Staedtler Noris 120 Lápiz de grafito, mina HB, cuerpo hexagonal amarillo y negro.',1,'Lápiz','lapiz.jpg',0.36,50,21,'Unidad','unidad',14);

INSERT INTO `producto` VALUES (231,'N/A','BIC Cristal',1,'N/A','Dispone de marcado CE','BIC Cristal Original Bolígrafo de punta de bola, punta mediana de 1 mm, cuerpo translúcido, tinta azul.',1,'Bolígrafo','boliBIC.jpg',0.20,50,21,'Unidad','unidad',14);

INSERT INTO `producto` VALUES (232,'N/A','Tapa de polipropileno flexible de 800 micras.',1,'N/A','Dispone de marcado CE','Esta agenda día página de espiral de la gama Dohe Syncro le permitirá organizar su día a día fácilmente dado que es un complemento imprescindible en su mesa o bolso para su trabajo diario.',1,'Agenda 2021','agenda.jpg',7.49,50,21,'Unidad','unidad',14);

INSERT INTO `producto` VALUES (233,'N/A','Cuaderno formato folio.',1,'N/A','Dispone de marcado CE','Tapa blanda de cartón con esquinas redondeadas. Espiral simple. Papel ecológico PEFC de 60 g/m²',1,'Cuaderno','cuaderno.jpg',1.49,50,21,'Unidad','unidad',14);
